### ISSUE TITLE
col幅統一

### ISSUE THREAD

**Issue by dym330** [yoppari-club/nagano-cake#65]
例）
1-12
管理者ジャンル一覧、管理者、商品一覧
2-11
注文履歴一覧
3-10
管理者会員一覧

**Comment by ghost** [comment]
カートアイテムをベースに統一

**Comment by ghost** [comment]
admin edit, index, new,show修正

**Comment by ghost** [comment]
customer shippingaddress edit,index修正

**Comment by ghost** [comment]
customers/items index show 修正
